server:
  port: 8002
spring:
  application:
    name: article
  datasource:
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: article
    prefer-ip-address: true

